### ISSUE TITLE
How to using spatie/laravel-backup

### ISSUE THREAD

**Issue by tnduc** [RasecRapsag/docker-compose-laravel-mongodb#1]
I use spatie / laravel-backup to backup the database.
when i run: `php artisan backup: run`

```
Backup failed because The dump process failed with exitcode 127 : Command not found : sh: mongodump: not found
.
#0 /code/vendor/spatie/db-dumper/src/DbDumper.php(246): Spatie\DbDumper\Exceptions\DumpFailed::processDidNotEndSuccessfully(Object(Symfony\Component\Process\Process))
#1 /code/vendor/spatie/db-dumper/src/Databases/MongoDb.php(37): Spatie\DbDumper\DbDumper->checkIfDumpWasSuccessFul(Object(Symfony\Component\Process\Process), '/code/storage/a...')
#2 /code/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(250): Spatie\DbDumper\Databases\MongoDb->dumpToFile('/code/storage/a...')
#3 [internal function]: Spatie\Backup\Tasks\Backup\BackupJob->Spatie\Backup\Tasks\Backup\{closure}(Object(Spatie\DbDumper\Databases\MongoDb), 'mongodb')
#4 /code/vendor/laravel/framework/src/Illuminate/Support/Collection.php(1122): array_map(Object(Closure), Array, Array)
#5 /code/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(253): Illuminate\Support\Collection->map(Object(Closure))
#6 /code/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(167): Spatie\Backup\Tasks\Backup\BackupJob->dumpDatabases()

```

What do I need to do to make it work.

**Comment by rrapsag** [comment]
Hi!

The mongodb-tools package was not installed in the container 'console'. In the etc/docker/Dockerfile.console file, you can change the line:

RUN apk --update add curl mongodb npm \

to:

RUN apk --update add curl mongodb mongodb-tools npm \

And for rebuild the image, follow the steps:

$ docker-compose down
$ docker rmi console
$ docker-compose up -d

Hope this helps.

**Comment by tnduc** [comment]
It worked, thank you, I needed more `php7-pdo php7-zip php7-simplexml`

**Comment by rrapsag** [comment]
I updated the repository by adding all of them.

**Comment by tnduc** [comment]
> I updated the repository by adding all of them.

Do you plan to add ssl, automatically renew ssl?

**Comment by rrapsag** [comment]
No. Why should I? I created this environment for development, are you using it in production?

**Comment by tnduc** [comment]
> No. Why should I? I created this environment for development, are you using it in production?

I use in production, is there any problem?

**Comment by rrapsag** [comment]
Not exactly. But, if you access from Internet, you'd better use nginx as a Reverse Proxy and configure ssl on it.

**Comment by tnduc** [comment]
I'm also having trouble with the nginx proxy, you can ask me here,
The frontend I build is static file, running with nginx with the backend, but the nginx proxy does not work.

```
server {
    listen 80;
    # gzip config
    gzip on;
    gzip_min_length 1k;
    gzip_comp_level 9;
    gzip_types text/plain application/javascript application/x-javascript text/css application/xml text/javascript application/x-httpd-php image/jpeg image/gif image/png;
    gzip_vary on;
    gzip_disable "MSIE [1-6]\.";

    server_name admin.localhost.test;
    root /var/www/dist;

    location / {
        # Used in conjunction with browserHistory
        try_files $uri $uri/ /index.html;

        # If you have resources, it is recommended to use https + http2 for a better experience with on-demand loading.
        # rewrite ^/(.*)$ https://preview.pro.ant.design/$1 permanent;

    }

    location /api {
        proxy_pass http://api.localhost.test;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   Host              api.localhost.test
        proxy_set_header   X-Real-IP         $remote_addr;
    }
}
```

I added `network_mod: host` in console docker compose and tried curl to api.localhost.test successfully, but at the frontend I found the proxy is not working, status returned 302, can you help me solve this problem?

**Comment by rrapsag** [comment]
Sorry! I'm not very good at setting up nginx. You should try this:

https://dev.to/domysee/setting-up-a-reverse-proxy-with-nginx-and-docker-compose-29jg

**Comment by tnduc** [comment]
I have a problem with the database connection.
If set .env file:
`DB_HOST=db` laravel CURD works
`DB_HOST=localhost`laravel migrate, laravel-backup works.

Can you explain to me why this error occurred, and how to fix it.

**Comment by rrapsag** [comment]
The environment was made for run commands inside the container 'console'. So, should have worked if you setted up DB_HOST=db!!
You can access the database through localhost, because I exposed the port outside the container.

$ make ps
db        docker-entrypoint.sh mongod     Up      **0.0.0.0:27017**->27017/tcp

I did this to access mongodb by the Robot 3T tool.

**Comment by tnduc** [comment]
If I set `DB_HOST=db`, I cannot run migrate or package laravel-packup?

**Comment by rrapsag** [comment]
Inside the console container yes, outside not.

**Comment by tnduc** [comment]
Sorry, but I don't understand, you can say more specifically, I have just used docker, I don't understand how it organizes and works.

**Comment by rrapsag** [comment]
But let's go! In docker-compose.yml file we define 4 services:

web: nginx webserver (port 80)
php: php interpreter (port 9000)
db: database mongo (port 27017)
console: shell for run commands

Usually these services connect internally by their names, so, they only communicate inside the docker. Do the test by removing in docker-compose.yml file:

```
    #ports:
    #  - "${NGINX_PORT}:80"

    #ports:
    #  - ${MONGO_PORT}:27017
```

Follow the steps:

```
$ make start
$ make ps

console   /bin/sh -c /bin/sh              Up               
db        docker-entrypoint.sh mongod     Up      27017/tcp
php       docker-php-entrypoint php-fpm   Up      9000/tcp 
web       nginx -g daemon off;            Up      80/tcp   
```

The ports are internal, if you try to access http://localhost or http://server_ip you will not be able to access. But, inside console container you will access the page:

```
$ make console
/code $ curl web
```

To get external access again, change in docker-compose.yml file:

```
    ports:
      - "${NGINX_PORT}:80"
```

Follow the steps:

```
# make down
$ make up
$ make ps

console   /bin/sh -c /bin/sh              Up                        
db        docker-entrypoint.sh mongod     Up      27017/tcp         
php       docker-php-entrypoint php-fpm   Up      9000/tcp          
web       nginx -g daemon off;            Up      0.0.0.0:80->80/tcp
```

Note that port 80 is linked to web's port 80. Now, you will be able to access through http://server_ip 

So, when 'php' reads DB_HOST=db, it connects to the mongodb in 'db'. If you set DB_HOST=localhost, 'php' thinks mongodb is installed in itself.

It's hard to explain.
